/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single discovered file entry returned to Node.js. */
export interface FileEntry {
  /** Absolute file path (forward slashes) */
  path: string
  /** File size in bytes */
  size: number
  /** File modification time in milliseconds since epoch */
  mtimeMs: number
}
/** Options for workspace scanning. */
export interface ScanOptions {
  /** Allowed file extensions (e.g. [".ts", ".js", ".py"]) */
  allowedExtensions: Array<string>
  /** Directory names to ignore (e.g. ["node_modules", ".git"]) */
  ignoredDirs: Array<string>
  /** Maximum number of files to return (safety cap) */
  maxFiles?: number
}
/**
 * Asynchronously scans a workspace directory for code files.
 *
 * Uses walkdir for traversal and rayon for parallel stat() calls.
 * Returns a Vec of FileEntry with normalized forward-slash paths.
 *
 * This function runs on a Tokio thread pool and does NOT block
 * the Node.js event loop.
 */
export declare function scanWorkspace(dir: string, options: ScanOptions): Promise<Array<FileEntry>>
/** Synchronous version for benchmarking. Avoid in production — use scan_workspace instead. */
export declare function scanWorkspaceSync(dir: string, options: ScanOptions): Array<FileEntry>
/** Input file for batch chunking. */
export interface ChunkInput {
  /** Absolute file path */
  filePath: string
  /** Workspace-relative path (forward slashes) */
  relativePath: string
}
/** A single text chunk produced from a source file. */
export interface TextChunk {
  /** Workspace-relative file path (forward slashes) */
  filePath: string
  /** Zero-based chunk index within the file */
  chunkIndex: number
  /** The actual text content of this chunk */
  content: string
}
/** Chunking configuration options. */
export interface ChunkOptions {
  /** Target chunk size in characters (default: 1000) */
  chunkSize?: number
  /** Overlap between adjacent chunks in characters (default: 200) */
  overlap?: number
  /** Minimum chunk length to include (default: 20) */
  minChunkLength?: number
}
/**
 * Reads and chunks multiple files in parallel using rayon.
 *
 * Each file is read from disk, split into overlapping text chunks
 * aligned to paragraph/line boundaries, and returned as a flat Vec.
 *
 * This replaces the sequential JS loop that called readFileSync +
 * chunkText() per file on the main thread.
 */
export declare function chunkFiles(files: Array<ChunkInput>, options?: ChunkOptions | undefined | null): Promise<Array<TextChunk>>
/** Reads a single file and chunks it. Convenience wrapper for incremental indexing. */
export declare function chunkSingleFile(filePath: string, relativePath: string, chunkSize?: number | undefined | null, overlap?: number | undefined | null): Array<TextChunk>
/** A single similarity match result returned to Node.js. */
export interface SimilarityResult {
  /** Index into the original vectors array */
  index: number
  /** Cosine similarity score (0.0 - 1.0 for normalized vectors) */
  score: number
}
/**
 * Computes cosine similarity between a query vector and a batch of vectors.
 *
 * Uses Rayon for data parallelism across CPU cores. Each dot product
 * computation is auto-vectorized by LLVM to use SIMD instructions
 * (SSE2/AVX2 on x86_64) when compiled with `opt-level = 3`.
 *
 * Returns the top-K results sorted by score descending, filtered
 * by a minimum threshold.
 *
 * This replaces the sequential JS loop in RAGQueryEngine that loaded
 * ALL embeddings and computed dot products one-by-one on the main thread.
 */
export declare function cosineSimilarityBatch(queryVec: Array<number>, allVectors: Array<Array<number>>, topK: number, threshold: number): Array<SimilarityResult>
/**
 * Optimized version that takes raw Float32 buffers instead of Vec<Vec<f64>>.
 *
 * This avoids the overhead of creating nested JS arrays. Instead, vectors
 * are passed as a single flat Float32Array buffer with a known dimension.
 *
 * Memory layout: [v0_d0, v0_d1, ..., v0_dN, v1_d0, v1_d1, ..., v1_dN, ...]
 */
export declare function cosineSimilarityBatchBuffer(queryVec: Array<number>, flatVectors: Buffer, vectorDim: number, numVectors: number, topK: number, threshold: number): Array<SimilarityResult>
/** Single-pair cosine similarity (for compatibility). */
export declare function cosineSimilarity(vecA: Array<number>, vecB: Array<number>): number
/** A single search match result returned to Node.js. */
export interface NativeSearchMatch {
  /** Workspace-relative file path (forward slashes) */
  file: string
  /** 1-based line number */
  line: number
  /** 1-based column number */
  column: number
  /** The trimmed content of the matching line */
  content: string
}
/** Search result container with metadata. */
export interface SearchResult {
  /** All matches found */
  matches: Array<NativeSearchMatch>
  /** Total number of matches (may exceed returned matches if truncated) */
  totalMatches: number
  /** Whether results were truncated at max_results */
  truncated: boolean
  /** Time elapsed in milliseconds */
  elapsedMs: number
}
/**
 * Performs a parallel, non-blocking file content search across a workspace.
 *
 * 1. Walks the directory tree (single-threaded, fast)
 * 2. Reads and searches files in parallel via rayon
 * 3. Returns matches sorted by file path, then line number
 *
 * This replaces the synchronous walkAndSearch() function in searchHandlers.ts
 * that used readdirSync + readFileSync on the main process IPC thread.
 */
export declare function searchFiles(dir: string, pattern: string, isRegex: boolean, caseSensitive: boolean, includeExts: Array<string>, excludeDirs: Array<string>, maxResults?: number | undefined | null): Promise<SearchResult>
